apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones
  namespace: reservas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificaciones
          image: sistema-reservas-resiliente-notificaciones:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones-service
  namespace: reservas-app
spec:
  selector:
    app: notificaciones
  ports:
    - port: 8004
      targetPort: 8004