apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas
  namespace: reservas-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: reservas
  template:
    metadata:
      labels:
        app: reservas
    spec:
      containers:
        - name: reservas
          image: sistema-reservas-resiliente-reservas:cb-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: INVENTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: reservas-config
                  key: INVENTORY_URL
            - name: PAYMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: reservas-config
                  key: PAYMENT_URL
            - name: NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: reservas-config
                  key: NOTIFICATION_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - reservas
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-service
  namespace: reservas-app
spec:
  selector:
    app: reservas
  ports:
    - port: 8001
      targetPort: 8001