apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas
  namespace: reservas-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: reservas

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  template:
    metadata:
      labels:
        app: reservas

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - reservas
              topologyKey: kubernetes.io/hostname

      containers:
        - name: reservas
          image: sistema-reservas-resiliente-reservas:notification-v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8001

          env:
            - name: INVENTORY_URL
              value: "http://inventario-service:8002"

            - name: PAYMENT_URL
              value: "http://pagos-service:8003"

            - name: NOTIFICATION_URL
              value: "http://notificaciones-service:8004"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: reservas-service
  namespace: reservas-app

spec:
  selector:
    app: reservas

  ports:
    - port: 8001
      targetPort: 8001